readjusted make test file

diff --git a/makego b/makego
--- a/makego
+++ b/makego
@@ -50,35 +50,6 @@ function generate_go_package_file {
         " > "${filename}"
 }
 
-function generate_test_file {
-    filename="${1}"
-    test_filename="${filename%.go}_test.go"
-
-    [[ -e "${test_filename}" ]] && {
-        echo "The file ${test_filename} exists, and can't be overwritten."
-        exit 1
-    }
-
-    # basic golang line to write to file
-    # package name is the same as the filename without the .go extension
-    package_name=$(basename "${filename}" .go)
-    echo "
-        package ${package_name}
-
-        import (
-            \"testing\"
-        )
-
-        func TestDefaultFunc(t *testing.T) {
-            t.Parallel()
-            result := 1 + 3
-            if result != 4 {
-                t.Errorf(\"Expected 4, got %d\", result)
-            }
-        }
-    " > "${test_filename}"
-}
-
 
 # write out a basic go file
 function generate_go_file() {
@@ -124,6 +95,11 @@ function format_code() {
 function make_a_test_file() {
     filename="${1}"
     filename="${filename%.*}"
+
+     [[ -e "${filename}" ]] && {
+         echo "The file ${filename} exists, and can't be overwritten."
+         exit 1
+     }
 
     echo "
         package ${filename}
